<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
    <RootNamespace>Consumo_Reducido_de_Agua_ahora_si_definitivo</RootNamespace>
    <Nullable>enable</Nullable>
    <EnableDefaultItems>true</EnableDefaultItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <!-- Exclude stray branch/build artifacts anywhere under 'solutions' from default item globs -->
    <DefaultItemExcludes>$(DefaultItemExcludes);solutions\**\*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <!-- Hard exclude any files under the 'solutions' directory to avoid compiling artifacts from other branches/projects -->
    <Compile Remove="solutions\**\*.cs" />
    <Page Remove="solutions\**\*.xaml" />
    <Resource Remove="solutions\**\*" />
    <EmbeddedResource Remove="solutions\**\*" />
    <None Remove="solutions\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Boton Iniciar sesion.png" />
    <None Remove="Boton Registrarse.png" />
    <None Remove="Captura de pantalla 2025-09-29 082544.png" />
    <None Remove="Captura de pantalla 2025-10-08 132404.png" />
    <None Remove="Captura de pantalla 2025-10-10 073526.png" />
    <None Remove="Casa.jpeg" />
    <None Remove="Casa2.png" />
    <None Remove="Configuracion texto.png" />
    <None Remove="Configuracion.png" />
    <None Remove="Correo.png" />
    <None Remove="descarga.png" />
    <None Remove="flecha.png" />
    <None Remove="Fondo Preguntas %282%29.png" />
    <None Remove="fondo preguntas.png" />
    <None Remove="Grafica barras.png" />
    <None Remove="Grafica lineas y puntos.png" />
    <None Remove="Image2.png" />
    <None Remove="Image3.png" />
    <None Remove="Image4.png" />
    <None Remove="Images\Help.png" />
    <None Remove="logo programa Pagina.png" />
    <None Remove="logo programa.png" />
    <None Remove="Logo.png" />
    <None Remove="Marea.png" />
    <None Remove="Menu Principal seleccionado.png" />
    <None Remove="Menu Principal.png" />
    <None Remove="Mes.png" />
    <None Remove="No.png" />
    <None Remove="Ojo.png" />
    <None Remove="perrito chivas.png" />
    <None Remove="Place Holder Foto.jpg" />
    <None Remove="Propio.jpg" />
    <None Remove="Propio.png" />
    <None Remove="Renta.jpeg" />
    <None Remove="Renta.png" />
    <None Remove="Reportar.png" />
    <None Remove="Semana.png" />
    <None Remove="Si.png" />
    <None Remove="teto-tetoris.gif" />
    <None Remove="Texto Inicio.png" />
    <None Remove="Usuario e invitados.png" />
    <None Remove="Vecindad.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />

    <!-- LiveCharts 2 WPF stack -->
    <PackageReference Include="LiveChartsCore" Version="2.0.0-rc6.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.0.0-rc6.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc6.1" />
    <PackageReference Include="Npgsql" Version="10.0.0-rc.1" />
    <PackageReference Include="QuestPDF" Version="2025.12.0-alpha2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0-rc.2.25502.107" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Captura de pantalla 2025-09-29 082544 - Copier.png" />
    <Resource Include="Images\Captura de pantalla 2025-10-08 132404 - Copier.png" />
    <Resource Include="Images\Casa2 - Copier.png" />
    <Resource Include="Images\Casa2.png" />
    <Resource Include="Images\Correo.png" />
    <Resource Include="Images\Empresa.jpg" />
    <Resource Include="Images\Boton Iniciar sesion.png" />
    <Resource Include="Images\Boton Registrarse.png" />
    <Resource Include="Images\Captura de pantalla 2025-09-29 082544.png" />
    <Resource Include="Images\Captura de pantalla 2025-10-08 132404.png" />
    <Resource Include="Images\Captura de pantalla 2025-10-10 073526.png" />
    <Resource Include="Images\Casa.jpeg" />
    <Resource Include="Images\Configuracion texto.png" />
    <Resource Include="Images\Configuracion.png" />
    <Resource Include="Images\descarga.png" />
    <Resource Include="Images\flecha.png" />
    <Resource Include="Images\Fondo Preguntas %282%29.png" />
    <Resource Include="Images\fondo preguntas.png" />
    <Resource Include="Images\Grafica barras.png" />
    <Resource Include="Images\Grafica lineas y puntos.png" />
    <Resource Include="Images\Help.png" />
    <Resource Include="Images\Image1.png" />
    <Resource Include="Images\Image2.png" />
    <Resource Include="Images\Image3.png" />
    <Resource Include="Images\Image4.png" />
    <Resource Include="Images\logo programa Pagina.png" />
    <Resource Include="Images\logo programa.png" />
    <Resource Include="Images\Logo.png" />
    <Resource Include="Images\Marea.png" />
    <Resource Include="Images\Menu Principal seleccionado.png" />
    <Resource Include="Images\Menu Principal.png" />
    <Resource Include="Images\Mes.png" />
    <Resource Include="Images\No.png" />
    <Resource Include="Images\Ojo.png" />
    <Resource Include="Images\perrito chivas.png" />
    <Resource Include="Images\Place Holder Foto.jpg" />
    <Resource Include="Images\Propio.jpg" />
    <Resource Include="Images\Propio.png" />
    <Resource Include="Images\Renta.jpeg" />
    <Resource Include="Images\Renta.png" />
    <Resource Include="Images\Reportar.png" />
    <Resource Include="Images\Semana.png" />
    <Resource Include="Images\Si.png" />
    <Resource Include="Images\teto-tetoris.gif" />
    <Resource Include="Images\Texto Inicio.png" />
    <Resource Include="Images\Usuario e invitados.png" />
    <Resource Include="Images\Vecindad.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings1.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings1.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Settings1.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings1.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <!--setso -->
    <Resource Remove="Images\LogoOpacidad15.png" />
    <Content Include="Images\LogoOpacidad15.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
